name: openvpn

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved isc-dhcp-client iproute2
      - name: Connect to Asee VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/opsvpn.ovpn
          client_key: ${{ secrets.OPSVPN_KEY }}
      - name: show network
        run: |
          ip address show
          ip route show
      - name: Ping Something local
        run: ping -c 3 10.148.0.100
      - name: Ping something in the same network
        run: ping -c 3 10.148.0.8
      - name: Ping UTMS
        run: |
           ping -c 3 10.148.2.10
           ping -c 3 10.148.2.1
      - name: ping PNB
        run: |
           ping -c 3 10.148.4.1
           ping -c 3 10.148.4.3
